// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PicPay.Simplificado.Infrastructure.Data.Context;

#nullable disable

namespace PicPay.Simplificado.Infrastructure.Migrations
{
    [DbContext(typeof(PicPaySimplificadoContext))]
    partial class PicPaySimplificadoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PicPay.Simplificado.Domain.Entidades.Transferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SucessoNaTransferencia")
                        .HasColumnType("bit");

                    b.Property<string>("TipoPagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioOrigemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transferencia");
                });

            modelBuilder.Entity("PicPay.Simplificado.Domain.Entidades.UsuarioComun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsuarioComun");
                });

            modelBuilder.Entity("PicPay.Simplificado.Domain.Entidades.UsuarioLojista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsuarioLojista");
                });

            modelBuilder.Entity("PicPay.Simplificado.Domain.Entidades.Transferencia", b =>
                {
                    b.OwnsOne("PicPay.Simplificado.Domain.ValueObjects.TransacaoDestino", "TransferenciaDestino", b1 =>
                        {
                            b1.Property<int>("TransferenciaId")
                                .HasColumnType("int");

                            b1.Property<string>("NomeCompleto")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("NomeDestino");

                            b1.HasKey("TransferenciaId");

                            b1.ToTable("Transferencia");

                            b1.WithOwner()
                                .HasForeignKey("TransferenciaId");
                        });

                    b.OwnsOne("PicPay.Simplificado.Domain.ValueObjects.TransacaoOrigem", "TransferenciaOrigem", b1 =>
                        {
                            b1.Property<int>("TransferenciaId")
                                .HasColumnType("int");

                            b1.Property<string>("NomeCompleto")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("NomeOrigem");

                            b1.HasKey("TransferenciaId");

                            b1.ToTable("Transferencia");

                            b1.WithOwner()
                                .HasForeignKey("TransferenciaId");
                        });

                    b.OwnsOne("PicPay.Simplificado.Domain.ValueObjects.TransferenciaSaldo", "TransferenciaSaldo", b1 =>
                        {
                            b1.Property<int>("TransferenciaId")
                                .HasColumnType("int");

                            b1.Property<double>("Saldo")
                                .HasColumnType("float")
                                .HasColumnName("SaldoTransferencia");

                            b1.HasKey("TransferenciaId");

                            b1.ToTable("Transferencia");

                            b1.WithOwner()
                                .HasForeignKey("TransferenciaId");
                        });

                    b.Navigation("TransferenciaDestino")
                        .IsRequired();

                    b.Navigation("TransferenciaOrigem")
                        .IsRequired();

                    b.Navigation("TransferenciaSaldo")
                        .IsRequired();
                });

            modelBuilder.Entity("PicPay.Simplificado.Domain.Entidades.UsuarioComun", b =>
                {
                    b.OwnsOne("PicPay.Simplificado.Domain.ValueObjects.DocEmail", "UsuarioEmail", b1 =>
                        {
                            b1.Property<int>("UsuarioComunId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioComunId");

                            b1.HasIndex("Email")
                                .IsUnique();

                            b1.ToTable("UsuarioComun");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioComunId");
                        });

                    b.OwnsOne("PicPay.Simplificado.Domain.ValueObjects.Nome", "UsuarioNome", b1 =>
                        {
                            b1.Property<int>("UsuarioComunId")
                                .HasColumnType("int");

                            b1.Property<string>("NomeCompleto")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.HasKey("UsuarioComunId");

                            b1.ToTable("UsuarioComun");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioComunId");
                        });

                    b.OwnsOne("PicPay.Simplificado.Domain.ValueObjects.Carteira", "UsuarioSaldo", b1 =>
                        {
                            b1.Property<int>("UsuarioComunId")
                                .HasColumnType("int");

                            b1.Property<double>("Saldo")
                                .HasColumnType("float")
                                .HasColumnName("Saldo");

                            b1.HasKey("UsuarioComunId");

                            b1.ToTable("UsuarioComun");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioComunId");
                        });

                    b.OwnsOne("PicPay.Simplificado.Domain.ValueObjects.DocCPF", "UsuarioCpf", b1 =>
                        {
                            b1.Property<int>("UsuarioComunId")
                                .HasColumnType("int");

                            b1.Property<string>("Cpf")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("nvarchar(14)")
                                .HasColumnName("CPF");

                            b1.HasKey("UsuarioComunId");

                            b1.HasIndex("Cpf")
                                .IsUnique();

                            b1.ToTable("UsuarioComun");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioComunId");
                        });

                    b.Navigation("UsuarioCpf")
                        .IsRequired();

                    b.Navigation("UsuarioEmail")
                        .IsRequired();

                    b.Navigation("UsuarioNome")
                        .IsRequired();

                    b.Navigation("UsuarioSaldo")
                        .IsRequired();
                });

            modelBuilder.Entity("PicPay.Simplificado.Domain.Entidades.UsuarioLojista", b =>
                {
                    b.OwnsOne("PicPay.Simplificado.Domain.ValueObjects.DocEmail", "UsuarioEmail", b1 =>
                        {
                            b1.Property<int>("UsuarioLojistaId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioLojistaId");

                            b1.HasIndex("Email")
                                .IsUnique();

                            b1.ToTable("UsuarioLojista");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioLojistaId");
                        });

                    b.OwnsOne("PicPay.Simplificado.Domain.ValueObjects.Nome", "UsuarioNome", b1 =>
                        {
                            b1.Property<int>("UsuarioLojistaId")
                                .HasColumnType("int");

                            b1.Property<string>("NomeCompleto")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.HasKey("UsuarioLojistaId");

                            b1.ToTable("UsuarioLojista");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioLojistaId");
                        });

                    b.OwnsOne("PicPay.Simplificado.Domain.ValueObjects.Carteira", "UsuarioSaldo", b1 =>
                        {
                            b1.Property<int>("UsuarioLojistaId")
                                .HasColumnType("int");

                            b1.Property<double>("Saldo")
                                .HasColumnType("float")
                                .HasColumnName("Saldo");

                            b1.HasKey("UsuarioLojistaId");

                            b1.ToTable("UsuarioLojista");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioLojistaId");
                        });

                    b.OwnsOne("PicPay.Simplificado.Domain.ValueObjects.DocCnpj", "UsuarioCnpj", b1 =>
                        {
                            b1.Property<int>("UsuarioLojistaId")
                                .HasColumnType("int");

                            b1.Property<string>("Cnpj")
                                .IsRequired()
                                .HasMaxLength(18)
                                .HasColumnType("nvarchar(18)")
                                .HasColumnName("CNPJ");

                            b1.HasKey("UsuarioLojistaId");

                            b1.HasIndex("Cnpj")
                                .IsUnique();

                            b1.ToTable("UsuarioLojista");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioLojistaId");
                        });

                    b.Navigation("UsuarioCnpj")
                        .IsRequired();

                    b.Navigation("UsuarioEmail")
                        .IsRequired();

                    b.Navigation("UsuarioNome")
                        .IsRequired();

                    b.Navigation("UsuarioSaldo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
