global using PicPay.Simplificado.Domain.Core.Interfaces.Base;
global using PicPay.Simplificado.Domain.Core.Interfaces.Commands.Result;
global using PicPay.Simplificado.Domain.Core.Interfaces.Commands.UsuarioComun;
global using PicPay.Simplificado.Domain.Core.Interfaces.Commands.UsuarioLojista;
global using PicPay.Simplificado.Domain.Core.Interfaces.Queries.Result;
global using PicPay.Simplificado.Domain.Core.Interfaces.Repositories;
global using PicPay.Simplificado.Domain.Entidades;
global using PicPay.Simplificado.Domain.ValueObjects;
global using System.Linq.Expressions;